name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Or your preferred Node.js version

    - name: Install dependencies
      run: npm install # or yarn install or pnpm install

    - name: Build
      run: npm run build # or yarn build or pnpm build

    # Add linting, testing, etc. steps here
    # - name: Lint
    #   run: npm run lint

    # - name: Test
    #   run: npm run test